---
to: <%= packageName %>/deploy/role_binding.yaml
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <%= packageName %>
subjects:
- kind: ServiceAccount
  name: <%= packageName %>
roleRef:
  kind: Role
  name: <%= packageName %>
  apiGroup: rbac.authorization.k8s.io
