---
unless_exists: true
to: <%= packageName %>/.prettierrc
---
{
  "singleQuote": true,
  "trailingComma": "all",
  "overrides": [
    {
      "files": "*.ts",
      "options": {
        "parser": "typescript"
      }
    }
  ]
}
