---
unless_exists: true
to: <%= packageName %>/tsconfig.release.json
---
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "rootDir": ".",
    "outDir": "build",
    "removeComments": true
  },
  "include": [
    "src/**/*"
  ]
}
