---
to: deploy/crds/<%= crdPath %>_crd.yaml
---
<%_
    kindPlural = h.inflection.pluralize(kind)
    kindPluralLower = kindPlural.toLowerCase()
    kindLower = kind.toLowerCase()
_%>
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: <%= kindPluralLower %>.<%= apiGroup %>
spec:
  group: <%= apiGroup %>
  names:
    kind: <%= kind %>
    listKind: <%= kind %>List
    plural: <%= kindPluralLower %>
    singular: <%= kindLower %>
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: <%= kind %> is the Schema for the <%= kindPluralLower %> API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: <%= kind %>Spec defines the desired state of <%= kind %>
          type: object
        status:
          description: <%= kind %>Status defines the observed state of <%= kind %>
          type: object
      type: object
  version: <%= version %>
  versions:
  - name: <%= version %>
    served: true
    storage: true

